name: Fetch Multiple Environment Variables from a Particular Environment

on:
  push:
    branches:
      - feature/testingdevdeploy
  
jobs:
  fetch:
    runs-on: ubuntu-latest
    environment: production  # Replace with your environment name

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch Variables from Repository
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: |
          echo "Fetching all environment variables and creating a .env file..."
          echo "$VARS_JSON" | jq -r 'to_entries | map("\(.key)=\(.value)")[]' > test.env

          echo "This is the content of test.env file:"
          cat test.env
