name: Test Environment Variables Fetching

on:
  push:
    branches:
      - feature/testingdevdeploy

jobs:
  test-env-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Test Environment Variable Fetching
      - name: Test Fetching All Environment Variables
        run: |
          echo "Fetching all environment variables from GitHub..."
          printenv > .env

          echo "Contents of the .env file:"
          cat .env
